# -*- coding: utf-8 -*-
"""Predicting Car Price with Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNeygdOKthT5oHiaw--_rIkHPn4xHbPy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
upload = files.upload()

df = pd.read_csv('/content/Data Harga Mobil.csv', index_col=0)
df

df.shape

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr

X = df[['highway-mpg']]
Y = df[['price']]

lr.fit(X, Y)

yhat = lr.predict(X)
yhat[0:5]

print('data', X[:1])
print()
print('Prediksi harganya:', lr.predict(X[:1]))

lr.intercept_

#slope
lr.coef_

data_prediksi =[[27]]

print('Harga yang didapat berdasarkan prediksi', lr.predict(data_prediksi))

Z = df[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]
lr.fit(Z, df['price'])

lr.intercept_

lr.coef_

data_prediksi = [[100, 2525, 100, 30]]
print('harga prediksi :', lr.predict(data_prediksi))