# -*- coding: utf-8 -*-
"""K-Means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xnDsx4LM68XsCZhXNSahv6UTrdUDXnmV
"""

from google.colab import files
upload = files.upload()

import pandas as pd
df_train = pd.read_csv('/content/train.csv')
df_test = pd.read_csv('/content/test.csv')
df_valid = pd.read_csv('/content/valid.csv')
df = df_train.append(df_valid, ignore_index=True)

df = df.append(df_test, ignore_index=True)

df.head()

df.label.value_counts()

import re

def cleanse(sent):
  string = sent.lower()
  string = re.sub(r'[^a-zA-Z]', ' ', string)
  return string
df['text'] = df['text'].apply(cleanse)

df.head()

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords as stopwords_scratch

list_stopwords = stopwords_scratch.words('indonesian')
list_stopwords_en = stopwords_scratch.words('english')
list_stopwords.extend(list_stopwords_en)
list_stopwords.extend(['ya', 'yg', 'yuk', 'ga', 'dah'])
stopwords = list_stopwords

stopwords[:3]

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words=stopwords)
X = vectorizer.fit_transform(df.text.to_list())

from sklearn.cluster import KMeans

true_k = 2
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=50, n_init=1)
model.fit(X)

order_centroids = model.cluster_centers_.argsort()[:, :20]
terms = vectorizer.get_feature_names()

for i in range(true_k):
  print("cluster %d:" %i),
  for ind in order_centroids[i, :10]:
    print('%s' % terms[ind])
  print()

from sklearn.metrics import silhouette_score

silhouette_score(X, labels=model.predict(X))

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
pca = PCA(n_components=2, random_state=0)
reduced_features = pca.fit_transform(X.toarray())

reduced_cluster_centers = pca.transform(model.cluster_centers_)

plt.scatter(reduced_features[:,0], reduced_features[:, 1], c=model.predict(X))
plt.scatter(reduced_cluster_centers[:,0], reduced_cluster_centers[:, 1], marker='X', s=200, c='r')